export const structureModal = {
  links: [
    { nameTranslate: 'На главную', name: 'main' },
    { nameTranslate: 'Вышивка', name: 'embroidery' },
    { nameTranslate: 'Рамка', name: 'frame' },
    { nameTranslate: 'Минимализм', name: 'minimalism' },
    { nameTranslate: 'Конструктор', name: 'constructor' },
    { nameTranslate: 'Авоськи', name: 'stringBag' },
    { nameTranslate: 'Броши', name: 'brooches' },
  ],
  embroidery: {
    title: 'Вышивка',
    products: [
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки' },
    ],
  },
  frame: {
    title: 'Рамка',
    products: [
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки' },
    ],
  },
  minimalism: {
    title: 'Минимализм',
    products: [
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки' },
    ],
  },
  constructor: {
    title: 'Конструктор',
    products: [
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки' },
    ],
  },
  stringBag: {
    title: 'Авоськи',
    products: [
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки' },
    ],
  },
  brooches: {
    title: 'Броши',
    products: [
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки' },
    ],
  },
};
