export const structureModal = {
  links: [
    { nameTranslate: 'На главную', name: 'main' },
    { nameTranslate: 'Вышивка', name: 'embroidery' },
    { nameTranslate: 'Рамка', name: 'frame' },
    { nameTranslate: 'Минимализм', name: 'minimalism' },
    { nameTranslate: 'Конструктор', name: 'constructor' },
    { nameTranslate: 'Авоськи', name: 'stringBag' },
    { nameTranslate: 'Броши', name: 'brooches' },
  ],
  embroidery: {
    title: 'Вышивка',
    products: [
      {
        image: 'Вышивка/Фрида/frida-1.jpg',
        name: 'Фрида',
        price: '370 BYN',
        id: 'embroidery-1',
        type: 'embroideryProducts',
      },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-2', type: 'embroideryProducts' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-3', type: 'embroideryProducts' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-4', type: 'embroideryProducts' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-5', type: 'embroideryProducts' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-6', type: 'embroideryProducts' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-7', type: 'embroideryProducts' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-8', type: 'embroideryProducts' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-9', type: 'embroideryProducts' },
    ],
  },
  frame: {
    title: 'Рамка',
    products: [
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-1' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-2' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-3' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-4' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-5' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-6' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-7' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-8' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-9' },
    ],
  },
  minimalism: {
    title: 'Минимализм',
    products: [
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-1' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-2' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-3' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-4' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-5' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-6' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-7' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-8' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-9' },
    ],
  },
  constructor: {
    title: 'Конструктор',
    products: [
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-1' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-2' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-3' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-4' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-5' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-6' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-7' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-8' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-9' },
    ],
  },
  stringBag: {
    title: 'Авоськи',
    products: [
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-1' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-2' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-3' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-4' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-5' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-6' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-7' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-8' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-9' },
    ],
  },
  brooches: {
    title: 'Броши',
    products: [
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-1' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-2' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-3' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-4' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-5' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-6' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-7' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-8' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-9' },
    ],
  },
};
