export const structureModal = {
  links: [
    { nameTranslate: 'На главную', name: 'main' },
    { nameTranslate: 'Вышивка', name: 'embroidery' },
    { nameTranslate: 'Рамка', name: 'frame' },
    { nameTranslate: 'Минимализм', name: 'minimalism' },
    { nameTranslate: 'Конструктор', name: 'constructor' },
    { nameTranslate: 'Авоськи', name: 'stringBag' },
    { nameTranslate: 'Броши', name: 'brooches' },
  ],
  embroidery: {
    title: 'Вышивка',
    products: [
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-1' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-2' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-3' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-4' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-5' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-6' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-7' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-8' },
      { image: 'embroidery.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'embroidery-9' },
    ],
  },
  embroideryProducts: [
    { id: 'embroidery-1', price: '', material: '' },
    { id: 'embroidery-2', price: '', material: '' },
    { id: 'embroidery-3', price: '', material: '' },
    { id: 'embroidery-4', price: '', material: '' },
    { id: 'embroidery-5', price: '', material: '' },
    { id: 'embroidery-6', price: '', material: '' },
    { id: 'embroidery-7', price: '', material: '' },
    { id: 'embroidery-8', price: '', material: '' },
    { id: 'embroidery-9', price: '', material: '' },
  ],
  frame: {
    title: 'Рамка',
    products: [
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
      { image: 'frame.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'frame-' },
    ],
  },
  minimalism: {
    title: 'Минимализм',
    products: [
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
      { image: 'minimalism.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'minimalism-' },
    ],
  },
  constructor: {
    title: 'Конструктор',
    products: [
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
      { image: 'constructor.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'constructor-' },
    ],
  },
  stringBag: {
    title: 'Авоськи',
    products: [
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
      { image: 'stringBag.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'stringBag-' },
    ],
  },
  brooches: {
    title: 'Броши',
    products: [
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
      { image: 'brooches.jpg', name: 'Аня', price: 'Скинь Фотки', id: 'brooches-' },
    ],
  },
};
